IF OBJECT_ID('FNDISTANCECALCULATION', 'FN') IS NOT NULL
BEGIN
	DROP FUNCTION FNDISTANCECALCULATION;
END
GO

CREATE FUNCTION FNDISTANCECALCULATION(
	@LATITUDE1 FLOAT,
	@LONGITUDE1 FLOAT,
	@LATITUDE2 FLOAT,
	@LONGITUDE2 FLOAT
)
RETURNS FLOAT
AS 
BEGIN

  DECLARE @PI FLOAT = PI();
  SET @LATITUDE1 = @LATITUDE1 * PI() / 180;
  SET @LONGITUDE1 = @LONGITUDE1 * PI() / 180;
  SET @LATITUDE2 = @LATITUDE2 * PI() / 180;
  SET @LONGITUDE2 = @LONGITUDE2 * PI() / 180;
  RETURN ACOS(
    COS(@LATITUDE1) * COS(@LONGITUDE1) * COS(@LATITUDE2) * COS(@LONGITUDE2) + COS(@LATITUDE1) *
    SIN(@LONGITUDE1) * COS(@LATITUDE2) * SIN(@LONGITUDE2) +	SIN(@LATITUDE1) * SIN(@LATITUDE2)
  ) * 6371 * 1000;

END
GO

-- Example
SELECT ROUND(DBO.FNDISTANCECALCULATION(55.7027212, 37.2123099, -29.6689667, 28.4978432), 2);
