DECLARE @TEST TABLE (
	ID INT,
	DS VARCHAR(100)
);

INSERT INTO @TEST
	(ID, DS)
VALUES
	(1, 'TEST1'),
	(2, 'TEST1'),
	(3, 'TEST1'),
	(4, 'TEST1');

DECLARE @VAR XML = (SELECT * FROM @TEST FOR XML AUTO);

SELECT @VAR;

-- Result:
<_x0040_TEST ID="1" DS="TEST1" />
<_x0040_TEST ID="2" DS="TEST2" />
<_x0040_TEST ID="3" DS="TEST3" />
<_x0040_TEST ID="4" DS="TEST4" />
