-- Generate a randon date
SELECT GETDATE() + (365 * 2 * RAND() - 365);
-- Result (variable): 2017-07-07 05:30:02.887

-- Generate a randon date inside a range
IF OBJECT_ID('VWRANDNUMBER', 'V') IS NOT NULL
BEGIN
	DROP VIEW VWRANDNUMBER;
END
GO

CREATE VIEW VWRANDNUMBER
AS
SELECT
	CAST(RAND()*10000 AS INT) AS RAND_NUMBER;
GO

IF OBJECT_ID('FNRANDDATE', 'FN') IS NOT NULL
BEGIN
	DROP FUNCTION FNRANDDATE;
END
GO

CREATE FUNCTION FNRANDDATE
(
	@FROMDATE DATE,
	@TODATE DATE
)
RETURNS DATE
AS
BEGIN

	DECLARE @DAYS_BETWEEN INT,
			@DAYS_RAND INT;

	SET @DAYS_BETWEEN = DATEDIFF(DAY, @FROMDATE, @TODATE);
	SET @DAYS_RAND = (SELECT RAND_NUMBER FROM VWRANDNUMBER) % @DAYS_BETWEEN;

	RETURN DATEADD(DAY, @DAYS_RAND, @FROMDATE)

END;
GO

-- Exemple of use
SELECT FORMAT(DBO.FNRANDDATE(GETDATE(), GETDATE()+180), 'dd/MM/yyyy');
-- Result (variable): 01/05/2018
