SELECT D.NAME
	,(
		SELECT X1 = MAX(BB.XX)
		FROM (
			SELECT XX = MAX(LAST_USER_SEEK)
			WHERE MAX(LAST_USER_SEEK) IS NOT NULL
			
			UNION ALL
			
			SELECT XX = MAX(LAST_USER_SCAN)
			WHERE MAX(LAST_USER_SCAN) IS NOT NULL
			
			UNION ALL
			
			SELECT XX = MAX(LAST_USER_LOOKUP)
			WHERE MAX(LAST_USER_LOOKUP) IS NOT NULL
			
			UNION ALL
			
			SELECT XX = MAX(LAST_USER_UPDATE)
			WHERE MAX(LAST_USER_UPDATE) IS NOT NULL
			) BB
		) AS LAST_ACCECS
FROM MASTER.DBO.SYSDATABASES D
LEFT OUTER JOIN SYS.DM_DB_INDEX_USAGE_STATS S ON D.DBID = S.DATABASE_ID
GROUP BY D.NAME
ORDER BY 2 DESC;
