SELECT TOP 20 SUBSTRING(QT.TEXT, (QS.STATEMENT_START_OFFSET / 2) + 1, (
			(
				CASE QS.STATEMENT_END_OFFSET
					WHEN - 1
						THEN DATALENGTH(QT.TEXT)
					ELSE QS.STATEMENT_END_OFFSET
					END - QS.STATEMENT_START_OFFSET
				) / 2
			) + 1) AS SQLTEXT
	,QS.EXECUTION_COUNT
	,QS.TOTAL_LOGICAL_READS
	,QS.LAST_LOGICAL_READS
	,QS.MIN_LOGICAL_READS
	,QS.MAX_LOGICAL_READS
	,QS.TOTAL_ELAPSED_TIME
	,QS.LAST_ELAPSED_TIME
	,QS.MIN_ELAPSED_TIME
	,QS.MAX_ELAPSED_TIME
	,QS.LAST_EXECUTION_TIME
	,QP.QUERY_PLAN
FROM SYS.DM_EXEC_QUERY_STATS QS
	CROSS APPLY SYS.DM_EXEC_SQL_TEXT(QS.SQL_HANDLE) QT
	CROSS APPLY SYS.DM_EXEC_QUERY_PLAN(QS.PLAN_HANDLE) QP
WHERE
	QT.ENCRYPTED = 0
ORDER BY QS.LAST_LOGICAL_READS DESC;
