/*Função para trazer datas*/

--SQL Server
/*Data Atual*/

select GETDATE();

/*Extrair*/

SELECT DAY(GETDATE());
SELECT DATEPART(DAY, GETDATE());
SELECT DATEPART(D, GETDATE()); -- Day of the month
SELECT DATEPART(DD, GETDATE());

SELECT MONTH(GETDATE());
SELECT YEAR(GETDATE());
SELECT DATEPART(YEAR, GETDATE());
SELECT DATEPART(YY, GETDATE());
SELECT DATEPART(YYYY, GETDATE());
SELECT DATEPART(QUARTER, GETDATE()); -- Of the month
SELECT DATEPART(DY, GETDATE()); -- Equal to DAYOFYEAR function

SELECT DATEPART(DAYOFYEAR, GETDATE());
SELECT DATEPART(QQ, GETDATE());
SELECT DATEPART(Q, GETDATE());
SELECT DATEPART(MONTH, GETDATE());
SELECT DATEPART(M, GETDATE());
SELECT DATEPART(MM, GETDATE());