/*Functions for date types*/

/*Sysdate/Actual date*/

SELECT GETDATE();
SELECT CURRENT_TIMESTAMP;

/*Extract*/

-- Day
SELECT DAY(GETDATE());
SELECT DATEPART(DAY, GETDATE());
SELECT DATEPART(D, GETDATE()); -- Day of the month
SELECT DATEPART(DD, GETDATE());
SELECT DATEPART(WEEKDAY, GETDATE());
SELECT DATEPART(DW, GETDATE());

-- Week of year
SELECT DATEPART(WEEK, GETDATE());
SELECT DATEPART(WK, GETDATE());
SELECT DATEPART(WW, GETDATE());

-- Week of Month
DECLARE @DATE DATETIME = GETDATE();
SELECT DATEDIFF(WEEK, DATEADD(MONTH, DATEDIFF(MONTH, 0, @DATE), 0), @DATE) + 1

-- First day of Month
SELECT DATEFROMPARTS(YEAR(GETDATE()), MONTH(GETDATE()), 1);
SELECT DATEADD(MONTH, DATEDIFF(MONTH, 0, GETDATE()), 0);

-- Last day of Month
SELECT EOMONTH(GETDATE());

-- Month
SELECT MONTH(GETDATE());
SELECT DATEPART(MONTH, GETDATE());
SELECT DATEPART(M, GETDATE());
SELECT DATEPART(MM, GETDATE());

-- Year
SELECT YEAR(GETDATE());
SELECT DATEPART(YEAR, GETDATE());
SELECT DATEPART(YY, GETDATE());
SELECT DATEPART(YYYY, GETDATE());

-- Quarter base on months of the year
SELECT DATEPART(QUARTER, GETDATE());
SELECT DATEPART(QQ, GETDATE());
SELECT DATEPART(Q, GETDATE());

-- Day of year
SELECT DATEPART(DY, GETDATE()); -- Equal to DAYOFYEAR function
SELECT DATEPART(DAYOFYEAR, GETDATE());
