/*LAST_VALUE AND FIRST_VALUE*/
SELECT
	SalesOrderId, CustomerID, TotalDue, 
	LAST_VALUE(TotalDue) OVER (ORDER BY TotalDue DESC
							   ROWS BETWEEN UNBOUNDED PRECEDING
							   AND UNBOUNDED FOLLOWING) AS [LAST_VALUE],
	FIRST_VALUE(TotalDue) OVER (ORDER BY TotalDue DESC) AS [FIRST_VALUE]
FROM Sales.SalesOrderHeader
ORDER BY TotalDue DESC;