SELECT
	IPADRESS AS ORIGINAL,
	PARSENAME(IPADRESS, 4) AS [FIRST FIELD],
	PARSENAME(IPADRESS, 3) AS [SECOND FIELD],
	PARSENAME(IPADRESS, 2) AS [THIRD FIELD],
	PARSENAME(IPADRESS, 1) AS [FOURTH FIELD]
FROM
(
	SELECT '10.1.2.165' AS IPADRESS
	UNION ALL
	SELECT '10.2.1.65' AS IPADRESS
	UNION ALL
	SELECT '192.168.0.1' AS IPADRESS
) [IP];