-- ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING

SELECT
	SalesOrderID ,
	CustomerID ,
	TotalDue ,
	SUM(TotalDue) OVER(ORDER BY TotalDue DESC) AS NormalSum ,
	SUM(TotalDue) OVER(ORDER BY TotalDue DESC
					   ROWS BETWEEN UNBOUNDED PRECEDING
					   AND UNBOUNDED FOLLOWING) AS GlobalSum ,
	SUM(TotalDue) OVER(ORDER BY TotalDue ASC
					   ROWS BETWEEN UNBOUNDED PRECEDING
					   AND 1 FOLLOWING) AS AlterSum , -- SUM for each collumn agregating
	AVG(TotalDue) OVER(ORDER BY TotalDue DESC) AS NormalAverage ,
	AVG(TotalDue) OVER(ORDER BY TotalDue DESC
					   ROWS BETWEEN UNBOUNDED PRECEDING
					   AND UNBOUNDED FOLLOWING) AS GlobalAverage ,
	MIN(TotalDue) OVER(ORDER BY TotalDue DESC) AS NormalMin ,
	MIN(TotalDue) OVER(ORDER BY TotalDue DESC
					   ROWS BETWEEN UNBOUNDED PRECEDING
					   AND UNBOUNDED FOLLOWING) AS GlobalMin ,
	MAX(TotalDue) OVER(ORDER BY TotalDue DESC) AS NormalMax ,
	MAX(TotalDue) OVER(ORDER BY TotalDue DESC
					   ROWS BETWEEN UNBOUNDED PRECEDING
					   AND UNBOUNDED FOLLOWING) AS GlobalMax
FROM Sales.SalesOrderHeader
ORDER BY TotalDue DESC;