/*Functions for time types*/

/*Sysdate/Actual time*/

SELECT GETDATE();
SELECT CURRENT_TIMESTAMP;

/*Extract*/

-- Hour
SELECT DATEPART(HOUR, GETDATE());
SELECT DATEPART(HH, GETDATE());

-- Minutes
SELECT DATEPART(MINUTE, GETDATE());
SELECT DATEPART(MI, GETDATE());
SELECT DATEPART(N, GETDATE());

-- Seconds
SELECT DATEPART(SECOND, GETDATE());
SELECT DATEPART(SS, GETDATE());
SELECT DATEPART(S, GETDATE());

-- Milisecond
SELECT DATEPART(MILLISECOND, GETDATE());
SELECT DATEPART(MS, GETDATE());

-- Microsecond
SELECT DATEPART(MICROSECOND, GETDATE());
SELECT DATEPART(MCS, GETDATE());

-- Nanosecond
SELECT DATEPART(NANOSECOND, GETDATE());
SELECT DATEPART(NS, GETDATE());